services:
  mongo:
    image: mongo
    container_name: nestjs-auth-mongo
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodata:/data/db
    networks:
      - nestjs-auth-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prerelease
    container_name: nestjs-auth-api
    environment:
      - PORT=${PORT}
      - NODE_ENV=delevopment
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - nestjs-auth-network
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${APP_HOST}:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mongo-express:
    image: mongo-express
    container_name: nestjs-auth-mongo-express
    restart: always
    ports:
      - '${ME_CONFIG_HOST_PORT}:${ME_CONFIG_CONTAINER_PORT}'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}
      - ME_CONFIG_BASICAUTH_ENABLED=${ME_CONFIG_BASICAUTH_ENABLED}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    networks:
      - nestjs-auth-network

networks:
  nestjs-auth-network:
    driver: bridge
    name: nestjs-auth-network
